services:
  api:
    build: .
    ports:
      - "5003:5000"
    environment:
      - PYTHONPATH=.
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "entrypoints.app:app"]

  event-consumer:
    build: .
    environment:
      - PYTHONPATH=.
    command: ["python", "entrypoints/event_consumer.py"]
